"""initial schema

Revision ID: 540eb200aacd
Revises:
Create Date: 2026-09-14 20:24:17.593594
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "540eb200aacd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("client_ip", sa.Text(), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(
            "ix_audit_events_actor_timestamp", ["actor", "timestamp"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_events_target"), ["target"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "blocked_sources",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("network", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("rate_limited", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("removal_reason", sa.Text(), nullable=True),
        sa.Column("backend", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocked_sources")),
    )
    with op.batch_alter_table("blocked_sources", schema=None) as batch_op:
        batch_op.create_index(
            "ix_blocked_sources_active_network", ["active", "network"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_blocked_sources_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_blocked_sources_network"), ["network"], unique=False)

    op.create_table(
        "incidents",
        sa.Column("incident_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column(
            "risk",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "categories",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "affected_sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "affected_destinations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "affected_services",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("correlation_rule", sa.Text(), nullable=True),
        sa.Column("detection_count", sa.Integer(), nullable=False),
        sa.Column(
            "timeline",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_to", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("sensor", sa.Text(), nullable=False),
        sa.Column("replay_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('open', 'investigating', 'contained', 'resolved', 'false_positive')",
            name=op.f("ck_incidents_status_valid"),
        ),
        sa.CheckConstraint(
            "risk_score >= 0 AND risk_score <= 100", name=op.f("ck_incidents_risk_range")
        ),
        sa.PrimaryKeyConstraint("incident_id", name=op.f("pk_incidents")),
    )
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incidents_last_seen"), ["last_seen"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_replay_id"), ["replay_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_risk_score"), ["risk_score"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_severity"), ["severity"], unique=False)
        batch_op.create_index(
            "ix_incidents_status_last_seen", ["status", "last_seen"], unique=False
        )

    op.create_table(
        "replays",
        sa.Column("replay_id", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "progress",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_replays_status_valid"),
        ),
        sa.PrimaryKeyConstraint("replay_id", name=op.f("pk_replays")),
    )
    with op.batch_alter_table("replays", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_replays_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_replays_status"), ["status"], unique=False)

    op.create_table(
        "response_actions",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("decision_id", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("executed", sa.Boolean(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("detection_id", sa.Text(), nullable=True),
        sa.Column("incident_id", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sensor", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_response_actions")),
        sa.UniqueConstraint("decision_id", name=op.f("uq_response_actions_decision_id")),
    )
    with op.batch_alter_table("response_actions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_response_actions_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_response_actions_decided_at"), ["decided_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_response_actions_detection_id"), ["detection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_response_actions_incident_id"), ["incident_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_response_actions_outcome"), ["outcome"], unique=False)
        batch_op.create_index(batch_op.f("ix_response_actions_target"), ["target"], unique=False)

    op.create_table(
        "rules",
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("rule_id", name=op.f("pk_rules")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "system_metrics",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sensor", sa.Text(), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=False),
        sa.Column("memory_bytes", sa.Float(), nullable=False),
        sa.Column("packets_processed", sa.BigInteger(), nullable=False),
        sa.Column("packets_dropped", sa.BigInteger(), nullable=False),
        sa.Column("detections", sa.Integer(), nullable=False),
        sa.Column("event_bus_dropped", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_metrics")),
    )
    with op.batch_alter_table("system_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_system_metrics_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "traffic_summaries",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sensor", sa.Text(), nullable=False),
        sa.Column("packets", sa.BigInteger(), nullable=False),
        sa.Column("bytes_total", sa.BigInteger(), nullable=False),
        sa.Column("packets_per_second", sa.Float(), nullable=False),
        sa.Column("detections", sa.Integer(), nullable=False),
        sa.Column("active_flows", sa.Integer(), nullable=False),
        sa.Column("tracked_sources", sa.Integer(), nullable=False),
        sa.Column(
            "protocols",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "top_sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "top_destinations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traffic_summaries")),
    )
    with op.batch_alter_table("traffic_summaries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_traffic_summaries_bucket_start"), ["bucket_start"], unique=False
        )
        batch_op.create_index(
            "ix_traffic_summaries_sensor_bucket", ["sensor", "bucket_start"], unique=False
        )

    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('viewer', 'analyst', 'admin')", name=op.f("ck_users_role_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        # Case-insensitive uniqueness. Note: an expression over the column, never over
        # the string literal 'username' (which autogenerate originally produced).
        batch_op.create_index("uq_users_username_lower", [sa.text("lower(username)")], unique=True)

    op.create_table(
        "detections",
        sa.Column("detection_id", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detector", sa.Text(), nullable=False),
        sa.Column("rule_name", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_ip", sa.Text(), nullable=False),
        sa.Column("destination_ip", sa.Text(), nullable=True),
        sa.Column("source_port", sa.Integer(), nullable=True),
        sa.Column("destination_port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.Text(), nullable=True),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("risk_band", sa.Text(), nullable=False),
        sa.Column(
            "risk",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("observation_window_seconds", sa.Float(), nullable=True),
        sa.Column("packet_count", sa.Integer(), nullable=True),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("incident_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sensor", sa.Text(), nullable=False),
        sa.Column("replay_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('new', 'acknowledged', 'false_positive', 'resolved')",
            name=op.f("ck_detections_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_detections_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.incident_id"],
            name=op.f("fk_detections_incident_id_incidents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("detection_id", name=op.f("pk_detections")),
    )
    with op.batch_alter_table("detections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_detections_destination_ip"), ["destination_ip"], unique=False
        )
        batch_op.create_index(
            "ix_detections_detector_timestamp", ["detector", "timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_detections_incident_id"), ["incident_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_detections_replay_id"), ["replay_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_detections_risk_score"), ["risk_score"], unique=False)
        batch_op.create_index(
            "ix_detections_severity_timestamp", ["severity", "timestamp"], unique=False
        )
        batch_op.create_index(
            "ix_detections_source_ip_timestamp", ["source_ip", "timestamp"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_detections_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("jti", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("jti", name=op.f("pk_refresh_tokens")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_expires_at"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("detections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_detections_timestamp"))
        batch_op.drop_index("ix_detections_source_ip_timestamp")
        batch_op.drop_index("ix_detections_severity_timestamp")
        batch_op.drop_index(batch_op.f("ix_detections_risk_score"))
        batch_op.drop_index(batch_op.f("ix_detections_replay_id"))
        batch_op.drop_index(batch_op.f("ix_detections_incident_id"))
        batch_op.drop_index("ix_detections_detector_timestamp")
        batch_op.drop_index(batch_op.f("ix_detections_destination_ip"))

    op.drop_table("detections")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("uq_users_username_lower")

    op.drop_table("users")
    with op.batch_alter_table("traffic_summaries", schema=None) as batch_op:
        batch_op.drop_index("ix_traffic_summaries_sensor_bucket")
        batch_op.drop_index(batch_op.f("ix_traffic_summaries_bucket_start"))

    op.drop_table("traffic_summaries")
    with op.batch_alter_table("system_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_metrics_timestamp"))

    op.drop_table("system_metrics")
    op.drop_table("settings")
    op.drop_table("rules")
    with op.batch_alter_table("response_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_response_actions_target"))
        batch_op.drop_index(batch_op.f("ix_response_actions_outcome"))
        batch_op.drop_index(batch_op.f("ix_response_actions_incident_id"))
        batch_op.drop_index(batch_op.f("ix_response_actions_detection_id"))
        batch_op.drop_index(batch_op.f("ix_response_actions_decided_at"))
        batch_op.drop_index(batch_op.f("ix_response_actions_action"))

    op.drop_table("response_actions")
    with op.batch_alter_table("replays", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_replays_status"))
        batch_op.drop_index(batch_op.f("ix_replays_created_at"))

    op.drop_table("replays")
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index("ix_incidents_status_last_seen")
        batch_op.drop_index(batch_op.f("ix_incidents_severity"))
        batch_op.drop_index(batch_op.f("ix_incidents_risk_score"))
        batch_op.drop_index(batch_op.f("ix_incidents_replay_id"))
        batch_op.drop_index(batch_op.f("ix_incidents_last_seen"))

    op.drop_table("incidents")
    with op.batch_alter_table("blocked_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blocked_sources_network"))
        batch_op.drop_index(batch_op.f("ix_blocked_sources_created_at"))
        batch_op.drop_index("ix_blocked_sources_active_network")

    op.drop_table("blocked_sources")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_audit_events_target"))
        batch_op.drop_index("ix_audit_events_actor_timestamp")
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
